---

- hosts: all
  gather_facts: false
  remote_user: jfgda
  #connection: network_cli
  vars:
    WAN_Command_List:
      - show version | i flash
      - show run | i template version
      - show crypto pki cert      
      - show environment all
      - show ip ospf int brief
      - show ip ospf neig
      - show cdp neighbors detail
      - show version
      - show license detail
      - show clock
      - show dmvpn
      - show bgp summary
      - show logging
      - show int status | inc connected
      - show arp
#      - Wpp-test
      - ping main1 repeat 1
      - ping main2 repeat 1
      - ping main3 repeat 1
      - ping main4 repeat 1
      - ping PPC1-CORE-SW repeat 1
      - ping PPC1-EXT-SW repeat
  register: output

- name: print output
  debug:
     var: output
