---

- hosts: all
  gather_facts: false
  remote_user: jfgda
  #connection: network_cli
  vars:
    WAN_Command_List:
      - show version | i flash
    register: output

  - name: print output
    debug:
      var: output
