---
- hosts: all
  gather_facts: true
  remote_user: jfgda
  tasks:
  - name: Shsow command
      command: show ntp associations 
      register: output
  - name: print output
    debug:
        var: output
