---
- hosts: all
  ignore_errors: yes
  collections:
   - cisco.ios
  tasks:
   - name: Backup
       command: show run 
     register: output
#       provider: "{{cli}}"
   - debug: 
           var: output.stdout_lines

