---
- hosts: all
  ignore_errors: yes
  collections:
   - cisco.ios
  tasks:
  - name: Backup
 #   ios_command:
 #       commands: show version
    register: output
#       provider: "{{cli}}"
  - debug: 
           var: output.stdout_lines

